### ISSUE TITLE
-erroraction stop always throws an error (An item with the same key has already been added)

### ISSUE THREAD

**Issue by insomniacc** [pspete/CredentialRetriever#18]
## Your Environment

* PowerShell Version: 5.1
* CredentialRetriever Branch & Version: v3.5.25
* CyberArk Version: Version 11.2.0 (11.2.0.18)

## Expected Behaviour

Get-AIMCredential -AppID "MyAppID" -Safe "MySafe" -UserName "Username" -RequiredProps Username **-erroraction stop**

This should produce the results without error on success.

## Current Behaviour

When using -erroraction stop
Regardless if the password is retrieved successfully or not, the following error is thrown:
Get-AIMCredential : Exception calling "Add" with "2" argument(s): "An item with the same key has already been added."

## Possible Solution

Additional error handling inside the function to prevent unnecessary errors when adding the same key.

## Steps to Reproduce (for bug reports)

1 . Add -erroraction stop

## Context

I was intending to use -erroraction stop so that my script would throw if theres a genuine error with this command, however an error is thrown even if it's successful.

**Comment by pspete** [comment]
Hi @insomniacc , many thanks for the reported issue.
The reason is likely [line 272](https://github.com/pspete/CredentialRetriever/blob/33cd0ca740365bde02b6428b5745702aa24c2e58/CredentialRetriever/Functions/Get-AIMCredential.ps1#L272) - I'll need to remind myself why it is coded that way, but can probably add some logic to see if erroraction is already present.

**Comment by pspete** [comment]
Resolved in 3.6.30 - thanks again for the report 👍

**Comment by insomniacc** [comment]
No problem, thanks for creating an awesome module and being responsive with patching issues too :) 👍
